Improved description of parsing errors
* ANTLRErrorListener callbacks from Lexer and Parser provide
  information about the error in parameter 'msg'.
* RecognitionException message often contains additional details
  that are worth including as a 'cause'.

Example: Template.parse("Invalid {{end bracket} }")
liqp.exceptions.LiquidException: lexer error "token recognition error at: '}'" on line 1, index 23
    Cause: LexerNoViableAltException('}')